#!/usr/bin/env bash

#place them in your .bash_aliases or maybe .bashrc
#or source this file for single session use

nwal(){ $HOME/.novo/bin/novo-cli getwalletinfo; }
ninfo(){ $HOME/.novo/bin/novo-cli getinfo; }
nhelp(){ $HOME/.novo/bin/novo-cli help; }
nstart(){ $HOME/.novo/bin/novo.sh; }
ncli(){ $HOME/.novo/bin/novo-cli $1 $2 $3 $4 $5 $6 $7 $8 $9; }
